version: '3'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  api-service:
    build: .
    ports:
      - "8080:80"
  uvicorn:
    image: uvicorn comprehensive_microservice.api_service:app
    ports:
      - "8000:8000"
