name: Continuous Integration
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: make init
      - name: Run lint
        run: make lint
      - name: Run Test
        run: make test
