name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: make init
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run lint
        run: make lint
  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Test
        run: make test
